//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TwistMsgMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/TwistMsg";
        public override string RosMessageName => k_RosMessageName;

        public float linear;
        public float angular;
        public bool stop;

        public TwistMsgMsg()
        {
            this.linear = 0.0f;
            this.angular = 0.0f;
            this.stop = false;
        }

        public TwistMsgMsg(float linear, float angular, bool stop)
        {
            this.linear = linear;
            this.angular = angular;
            this.stop = stop;
        }

        public static TwistMsgMsg Deserialize(MessageDeserializer deserializer) => new TwistMsgMsg(deserializer);

        private TwistMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.linear);
            deserializer.Read(out this.angular);
            deserializer.Read(out this.stop);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.linear);
            serializer.Write(this.angular);
            serializer.Write(this.stop);
        }

        public override string ToString()
        {
            return "TwistMsgMsg: " +
            "\nlinear: " + linear.ToString() +
            "\nangular: " + angular.ToString() +
            "\nstop: " + stop.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
